name: Retrieve AWS Secret and Variable

on:
  push:
    branches:
      - main
      - master
      - feature/*
      - develop

jobs:
  retrieve_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.REGION }}

      # Firstly, insert your secrets in AWS Secret Manager
      # Then, you can retrieve the secrets based on your secret-id
      # If you have multiple secret key and value pairs like mine, you can parse
      # the entire json object and print the values you'd like to display/use

      - name: Get Secret Object
        run: |
          secret_object=$(aws secretsmanager get-secret-value --secret-id dev/sharir/id --query SecretString --output json)

          # Parse specific keys from the secret object
          secret_value_food=$(echo "$secret_object" | jq -r '. | fromjson | .sharir_food')
          secret_value_drink=$(echo "$secret_object" | jq -r '. | fromjson | .sharir_drink')

          echo "Secret value Food is: $secret_value_food"
          echo "Secret value Drink is: $secret_value_drink"
          

  retrieve_parameters:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.REGION }}

      # Firstly, insert your parameter in AWS Systems Manager > Parameter Store
      # Then, you can retrieve the parameters using aws ssm get-parameter command

      - name: Get parameter object
        run: |
          motorcycle_value=$(aws ssm get-parameter --name sharir_motorcycle --query Parameter.Value --output text)
          echo "Sharir's motorcycle is: $motorcycle_value" 

